// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtRnI64wEo9WOFtSuTsnjNHQYs4voAwrQ',
    appId: '1:406202220091:web:838c11069f7952dfbda61e',
    messagingSenderId: '406202220091',
    projectId: 'hader-9f8a3',
    authDomain: 'hader-9f8a3.firebaseapp.com',
    storageBucket: 'hader-9f8a3.firebasestorage.app',
    measurementId: 'G-417JC6PW5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzd1-cqEVupvX_nuGT9FYRd3sK3k1SjWg',
    appId: '1:406202220091:android:6a28dee38ee94161bda61e',
    messagingSenderId: '406202220091',
    projectId: 'hader-9f8a3',
    storageBucket: 'hader-9f8a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0jy4rxGvmIZhrrBYGl7Ja7NUKr6G4QWA',
    appId: '1:406202220091:ios:823955de04c752fdbda61e',
    messagingSenderId: '406202220091',
    projectId: 'hader-9f8a3',
    storageBucket: 'hader-9f8a3.firebasestorage.app',
    iosBundleId: 'com.example.haderPharmMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0jy4rxGvmIZhrrBYGl7Ja7NUKr6G4QWA',
    appId: '1:406202220091:ios:823955de04c752fdbda61e',
    messagingSenderId: '406202220091',
    projectId: 'hader-9f8a3',
    storageBucket: 'hader-9f8a3.firebasestorage.app',
    iosBundleId: 'com.example.haderPharmMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtRnI64wEo9WOFtSuTsnjNHQYs4voAwrQ',
    appId: '1:406202220091:web:51d58ff33fd93568bda61e',
    messagingSenderId: '406202220091',
    projectId: 'hader-9f8a3',
    authDomain: 'hader-9f8a3.firebaseapp.com',
    storageBucket: 'hader-9f8a3.firebasestorage.app',
    measurementId: 'G-D0EC2LEM92',
  );
}
